"""Aggregate bench results into bench/logs/dashboard-data.js for index.html.

Idempotent — safe to call any time. The orchestrator (`run_bench.py`) calls
this at batch start, after every combo, and at the end of the LLM review pass,
so a manual browser refresh always shows the latest state without polling.

Manual invocation:
    python bench/build_dashboard.py    # rebuilds from current state

The output is a plain JavaScript file declaring `window.BENCH_DATA = {…}`.
`bench/index.html` loads it via a normal `<script>` tag so the dashboard
works under both `file://` and `http://` URLs.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
BENCH_DIR = REPO_ROOT / "bench"
LOGS_DIR = BENCH_DIR / "logs"
RUNS_DIR = LOGS_DIR / "runs"
OUT_PATH = LOGS_DIR / "dashboard-data.js"
LIVE_PATH = LOGS_DIR / ".bench-live.json"


def _load_runs() -> list[dict]:
    """Load every run JSON from logs/runs/, sorted newest-first by run_id."""
    if not RUNS_DIR.exists():
        return []
    runs: list[dict] = []
    for path in sorted(RUNS_DIR.glob("*.json")):
        try:
            runs.append(json.loads(path.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, OSError) as exc:
            print(f"[dashboard] skipping unreadable {path.name}: {exc}", file=sys.stderr)
            continue
    return sorted(runs, key=lambda r: r.get("run_id", ""), reverse=True)


def _load_latest_findings() -> str:
    """Return the markdown body of the most recent findings_*.md, or empty."""
    candidates = sorted(LOGS_DIR.glob("findings_*.md"), reverse=True)
    if not candidates:
        return ""
    try:
        return candidates[0].read_text(encoding="utf-8")
    except OSError:
        return ""


def _load_live() -> Optional[dict]:
    """Return the current live-progress state, or None if no batch is active.

    The file is written by `bench/run_bench.py:_live_ticker` every ~15s during
    a combo and replaced with `{"active": false, ...}` at batch end.
    """
    if not LIVE_PATH.exists():
        return None
    try:
        return json.loads(LIVE_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _group_by_batch(runs: list[dict]) -> tuple[list[str], dict[str, list[dict]]]:
    """Bucket runs by batch_id. Return (sorted-newest-first batch_ids, mapping)."""
    batches: dict[str, list[dict]] = {}
    for r in runs:
        bid = r.get("batch_id") or "unknown"
        batches.setdefault(bid, []).append(r)
    sorted_ids = sorted(batches.keys(), reverse=True)
    return sorted_ids, batches


def _count_verdicts(runs: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for r in runs:
        v = r.get("verdict") or "UNKNOWN"
        counts[v] = counts.get(v, 0) + 1
    return counts


def build() -> dict:
    """Aggregate all run JSONs + latest findings into the dashboard payload."""
    runs = _load_runs()
    sorted_batch_ids, by_batch = _group_by_batch(runs)
    latest_findings = _load_latest_findings()
    latest_batch: dict | None = None
    if sorted_batch_ids:
        bid = sorted_batch_ids[0]
        latest_batch = {
            "batch_id": bid,
            "run_ids": [r.get("run_id") for r in by_batch[bid]],
            "verdicts": _count_verdicts(by_batch[bid]),
            "findings_md": latest_findings,
        }
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_runs": len(runs),
        "total_batches": len(sorted_batch_ids),
        "has_data": len(runs) > 0,
        "verdict_counts": _count_verdicts(runs),
        "runs": runs,
        "latest_batch": latest_batch,
        "live": _load_live(),
    }


def write(data: dict, out_path: Path = OUT_PATH) -> Path:
    """Serialise the payload as `window.BENCH_DATA = {…};` at out_path."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(data, indent=2, default=str, ensure_ascii=False)
    out_path.write_text(
        "// Auto-generated by bench/build_dashboard.py — do not edit by hand.\n"
        "// Re-run `python bench/build_dashboard.py` (or any bench batch)\n"
        "// to refresh.\n"
        f"window.BENCH_DATA = {payload};\n",
        encoding="utf-8",
    )
    return out_path


if __name__ == "__main__":
    path = write(build())
    print(f"[dashboard] wrote {path.relative_to(REPO_ROOT)}", file=sys.stderr)
